name: Publish Docker image openssh-server

on:
  workflow_dispatch:
    inputs:
      openssh_server_version:
        description: 'openssh-server version'
        required: true
        type: string

jobs:
  push_piko_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: openssh-server/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/openssh-server:${{ inputs.openssh_server_version }}-py3
          platforms: linux/amd64,linux/arm64
          build-args: |
            OPENSSH_SERVER_VERSION=${{ inputs.openssh_server_version }}
