name: Publish Docker image NFS Ganesha

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'App version'
        required: false
        type: string

jobs:
  push_nfs_ganesha_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: nfs-ganesha/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nfs-ganesha:${{ inputs.app_version }}
          platforms: linux/amd64
          build-args: |
            APP_VERSION=${{ inputs.app_version }}
